### PR TITLE
Added installation to makefile

### PR DESCRIPTION
**Pull request by ghost**
I think it would be beneficial to install the lib instead of compiling in the project each run.

### CODE REVIEW

**Comment by 173210** [comment]
PSP2SDK is not always defined. (Actually I don't) :-1:

**Comment by minPSVSDK** [comment]
I think that if it's as a separate target it should be fine. Since no one has to install it, they can if they want.

**Comment by ghost** [comment]
1. Just add it to environment variables?
2. You don't HAVE to install it. You can use as it sits now.

**Comment by 173210** [comment]
Yes, it's works fine just by setting $(PSP2SDK). And it7s also possible to install by copying those files. Does it make any difference?

**Comment by ghost** [comment]
I added it to NES4Vita earlier and got compilation issues. It couldn't link the stub even though it was correct in the makefile. Installing it like this fixed it.

error:  http://privatepaste.com/2a90c57f1f
Makefile:  http://privatepaste.com/8149253ad1

**Comment by 173210** [comment]
I have no idea. But it's prohibited (or not recommended) to change those values in homebrews.

**Comment by minPSVSDK** [comment]
For now I think it's better to stick with not installing them into the SDK.

**Pull request closed without merging**
